name: Build Base Image
on:
  push:
    paths:
      - 'alldata/bblab_site/account/'
      - 'alldata/bblab_site/bblab_site/'
      - 'alldata/bblab_site/depend/'
      - 'alldata/bblab_site/templates/'
      - 'alldata/bblab_site/requirements.txt'
      - 'dockerfiles/bbtools.dockerfile'
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: base
